[2024-05-07T11:29:53.301+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-07T11:29:53.328+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_and_write_data_to_json.fetch_data_and_write_to_json scheduled__2023-12-30T00:00:00+00:00 [queued]>
[2024-05-07T11:29:53.339+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_and_write_data_to_json.fetch_data_and_write_to_json scheduled__2023-12-30T00:00:00+00:00 [queued]>
[2024-05-07T11:29:53.340+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-05-07T11:29:53.363+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): fetch_data_and_write_to_json> on 2023-12-30 00:00:00+00:00
[2024-05-07T11:29:53.372+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=4519) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-07T11:29:53.376+0000] {standard_task_runner.py:63} INFO - Started process 4537 to run task
[2024-05-07T11:29:53.374+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'fetch_and_write_data_to_json', 'fetch_data_and_write_to_json', 'scheduled__2023-12-30T00:00:00+00:00', '--job-id', '1639', '--raw', '--subdir', 'DAGS_FOLDER/newcris.py', '--cfg-path', '/tmp/tmpvomrb5cb']
[2024-05-07T11:29:53.379+0000] {standard_task_runner.py:91} INFO - Job 1639: Subtask fetch_data_and_write_to_json
[2024-05-07T11:29:53.438+0000] {task_command.py:426} INFO - Running <TaskInstance: fetch_and_write_data_to_json.fetch_data_and_write_to_json scheduled__2023-12-30T00:00:00+00:00 [running]> on host e8691f41e037
[2024-05-07T11:29:53.563+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fetch_and_write_data_to_json' AIRFLOW_CTX_TASK_ID='fetch_data_and_write_to_json' AIRFLOW_CTX_EXECUTION_DATE='2023-12-30T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-30T00:00:00+00:00'
[2024-05-07T11:29:53.567+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-07T11:29:53.945+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-07T11:29:53.946+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/newcris.py", line 22, in fetch_data_and_write_to_json
    with open(output_file_path, 'w') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/YtkaB/PycharmProjects/air/airflow_python_dag/dags'
[2024-05-07T11:29:53.958+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=fetch_and_write_data_to_json, task_id=fetch_data_and_write_to_json, execution_date=20231230T000000, start_date=20240507T112953, end_date=20240507T112953
[2024-05-07T11:29:53.973+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 1639 for task fetch_data_and_write_to_json ([Errno 2] No such file or directory: 'C:/Users/YtkaB/PycharmProjects/air/airflow_python_dag/dags'; 4537)
[2024-05-07T11:29:53.992+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-07T11:29:54.009+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-07T11:29:54.011+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
