[2024-05-07T11:13:30.236+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-07T11:13:30.268+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_and_write_data_to_json.fetch_data_and_write_to_json scheduled__2023-10-19T00:00:00+00:00 [queued]>
[2024-05-07T11:13:30.280+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_and_write_data_to_json.fetch_data_and_write_to_json scheduled__2023-10-19T00:00:00+00:00 [queued]>
[2024-05-07T11:13:30.282+0000] {taskinstance.py:2303} INFO - Starting attempt 2 of 2
[2024-05-07T11:13:30.307+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): fetch_data_and_write_to_json> on 2023-10-19 00:00:00+00:00
[2024-05-07T11:13:30.317+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=3976) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-07T11:13:30.319+0000] {standard_task_runner.py:63} INFO - Started process 3983 to run task
[2024-05-07T11:13:30.319+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'fetch_and_write_data_to_json', 'fetch_data_and_write_to_json', 'scheduled__2023-10-19T00:00:00+00:00', '--job-id', '1524', '--raw', '--subdir', 'DAGS_FOLDER/newcris.py', '--cfg-path', '/tmp/tmpbhszzn6j']
[2024-05-07T11:13:30.321+0000] {standard_task_runner.py:91} INFO - Job 1524: Subtask fetch_data_and_write_to_json
[2024-05-07T11:13:30.384+0000] {task_command.py:426} INFO - Running <TaskInstance: fetch_and_write_data_to_json.fetch_data_and_write_to_json scheduled__2023-10-19T00:00:00+00:00 [running]> on host e8691f41e037
[2024-05-07T11:13:30.495+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fetch_and_write_data_to_json' AIRFLOW_CTX_TASK_ID='fetch_data_and_write_to_json' AIRFLOW_CTX_EXECUTION_DATE='2023-10-19T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-10-19T00:00:00+00:00'
[2024-05-07T11:13:30.497+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-07T11:13:30.825+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-07T11:13:30.826+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/newcris.py", line 22, in fetch_data_and_write_to_json
    with open(output_file_path, 'w') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/YtkaB/PycharmProjects/air/airflow_python_dag/dags'
[2024-05-07T11:13:30.844+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=fetch_and_write_data_to_json, task_id=fetch_data_and_write_to_json, execution_date=20231019T000000, start_date=20240507T111330, end_date=20240507T111330
[2024-05-07T11:13:30.862+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 1524 for task fetch_data_and_write_to_json ([Errno 2] No such file or directory: 'C:/Users/YtkaB/PycharmProjects/air/airflow_python_dag/dags'; 3983)
[2024-05-07T11:13:30.895+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-07T11:13:30.917+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-07T11:13:30.920+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
