[2024-05-15T08:01:53.258+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-15T08:01:53.286+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_and_parse_cris_data.parse_cris_data scheduled__2024-05-13T15:00:00+00:00 [queued]>
[2024-05-15T08:01:53.296+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_and_parse_cris_data.parse_cris_data scheduled__2024-05-13T15:00:00+00:00 [queued]>
[2024-05-15T08:01:53.297+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-05-15T08:01:53.314+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): parse_cris_data> on 2024-05-13 15:00:00+00:00
[2024-05-15T08:01:53.322+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=2386) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-15T08:01:53.324+0000] {standard_task_runner.py:63} INFO - Started process 2407 to run task
[2024-05-15T08:01:53.325+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'fetch_and_parse_cris_data', 'parse_cris_data', 'scheduled__2024-05-13T15:00:00+00:00', '--job-id', '2509', '--raw', '--subdir', 'DAGS_FOLDER/cris.py', '--cfg-path', '/tmp/tmp_3pzil4l']
[2024-05-15T08:01:53.328+0000] {standard_task_runner.py:91} INFO - Job 2509: Subtask parse_cris_data
[2024-05-15T08:01:53.382+0000] {task_command.py:426} INFO - Running <TaskInstance: fetch_and_parse_cris_data.parse_cris_data scheduled__2024-05-13T15:00:00+00:00 [running]> on host e8691f41e037
[2024-05-15T08:01:53.504+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fetch_and_parse_cris_data' AIRFLOW_CTX_TASK_ID='parse_cris_data' AIRFLOW_CTX_EXECUTION_DATE='2024-05-13T15:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-13T15:00:00+00:00'
[2024-05-15T08:01:53.507+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-15T08:01:53.508+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-15T08:01:53.508+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: parse_cris_data_and_save() missing 1 required positional argument: 'data'
[2024-05-15T08:01:53.520+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=fetch_and_parse_cris_data, task_id=parse_cris_data, execution_date=20240513T150000, start_date=20240515T080153, end_date=20240515T080153
[2024-05-15T08:01:53.538+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 2509 for task parse_cris_data (parse_cris_data_and_save() missing 1 required positional argument: 'data'; 2407)
[2024-05-15T08:01:53.579+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-15T08:01:53.615+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-15T08:01:53.617+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
