[2024-05-15T08:01:13.622+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-15T08:01:13.645+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_and_parse_cris_data.parse_cris_data scheduled__2024-05-12T17:00:00+00:00 [queued]>
[2024-05-15T08:01:13.652+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_and_parse_cris_data.parse_cris_data scheduled__2024-05-12T17:00:00+00:00 [queued]>
[2024-05-15T08:01:13.653+0000] {taskinstance.py:2303} INFO - Starting attempt 2 of 2
[2024-05-15T08:01:13.666+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): parse_cris_data> on 2024-05-12 17:00:00+00:00
[2024-05-15T08:01:13.676+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=2280) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-15T08:01:13.678+0000] {standard_task_runner.py:63} INFO - Started process 2285 to run task
[2024-05-15T08:01:13.678+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'fetch_and_parse_cris_data', 'parse_cris_data', 'scheduled__2024-05-12T17:00:00+00:00', '--job-id', '2473', '--raw', '--subdir', 'DAGS_FOLDER/cris.py', '--cfg-path', '/tmp/tmpsp9vk__j']
[2024-05-15T08:01:13.682+0000] {standard_task_runner.py:91} INFO - Job 2473: Subtask parse_cris_data
[2024-05-15T08:01:13.730+0000] {task_command.py:426} INFO - Running <TaskInstance: fetch_and_parse_cris_data.parse_cris_data scheduled__2024-05-12T17:00:00+00:00 [running]> on host e8691f41e037
[2024-05-15T08:01:13.837+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fetch_and_parse_cris_data' AIRFLOW_CTX_TASK_ID='parse_cris_data' AIRFLOW_CTX_EXECUTION_DATE='2024-05-12T17:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-12T17:00:00+00:00'
[2024-05-15T08:01:13.839+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-15T08:01:13.839+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-15T08:01:13.840+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: parse_cris_data_and_save() missing 1 required positional argument: 'data'
[2024-05-15T08:01:13.848+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=fetch_and_parse_cris_data, task_id=parse_cris_data, execution_date=20240512T170000, start_date=20240515T080113, end_date=20240515T080113
[2024-05-15T08:01:13.859+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 2473 for task parse_cris_data (parse_cris_data_and_save() missing 1 required positional argument: 'data'; 2285)
[2024-05-15T08:01:13.892+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-15T08:01:13.915+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-15T08:01:13.919+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
