[2024-05-07T09:01:26.703+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-07T09:01:26.759+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_and_write_data_to_json.fetch_data_and_write_to_json scheduled__2022-12-08T00:00:00+00:00 [queued]>
[2024-05-07T09:01:26.786+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_and_write_data_to_json.fetch_data_and_write_to_json scheduled__2022-12-08T00:00:00+00:00 [queued]>
[2024-05-07T09:01:26.787+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-05-07T09:01:26.855+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): fetch_data_and_write_to_json> on 2022-12-08 00:00:00+00:00
[2024-05-07T09:01:26.872+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=333) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-07T09:01:26.875+0000] {standard_task_runner.py:63} INFO - Started process 359 to run task
[2024-05-07T09:01:26.880+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'fetch_and_write_data_to_json', 'fetch_data_and_write_to_json', 'scheduled__2022-12-08T00:00:00+00:00', '--job-id', '871', '--raw', '--subdir', 'DAGS_FOLDER/newcris.py', '--cfg-path', '/tmp/tmp9gvdnco_']
[2024-05-07T09:01:26.887+0000] {standard_task_runner.py:91} INFO - Job 871: Subtask fetch_data_and_write_to_json
[2024-05-07T09:01:27.016+0000] {task_command.py:426} INFO - Running <TaskInstance: fetch_and_write_data_to_json.fetch_data_and_write_to_json scheduled__2022-12-08T00:00:00+00:00 [running]> on host e8691f41e037
[2024-05-07T09:01:27.243+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fetch_and_write_data_to_json' AIRFLOW_CTX_TASK_ID='fetch_data_and_write_to_json' AIRFLOW_CTX_EXECUTION_DATE='2022-12-08T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2022-12-08T00:00:00+00:00'
[2024-05-07T09:01:27.250+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-07T09:01:30.799+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-07T09:01:30.800+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/newcris.py", line 22, in fetch_data_and_write_to_json
    with open(output_file_path, 'w') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/YtkaB/PycharmProjects/air/airflow_python_dag/dags'
[2024-05-07T09:01:30.819+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=fetch_and_write_data_to_json, task_id=fetch_data_and_write_to_json, execution_date=20221208T000000, start_date=20240507T090126, end_date=20240507T090130
[2024-05-07T09:01:30.845+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 871 for task fetch_data_and_write_to_json ([Errno 2] No such file or directory: 'C:/Users/YtkaB/PycharmProjects/air/airflow_python_dag/dags'; 359)
[2024-05-07T09:01:30.874+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-07T09:01:30.905+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-07T09:01:30.908+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
